language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: nightly

sudo: true

before_install:
  # Parallel download
  - sudo apt-get update -qq
  - sudo apt-get install aria2 curl -y

  # Retrieves and extracts the DB2 binaries
  - travis_retry export DOWNLOAD_LINK=$(phantomjs --ssl-protocol=tlsv1 download.js | tail -1 | grep http)
  - cd /tmp
  - travis_retry aria2c -x 16 ${DOWNLOAD_LINK}
  - DOWNLOAD_FILE=$(ls *.tar.gz)
  - tar zxvf ${DOWNLOAD_FILE}

  # INSTALL
  # Install the required libraries
  - sudo apt-get install libaio1 lib32stdc++6 -y
  - sudo apt-get install -qq libpam-ldap:i386
  - sudo ln -s /lib/i386-linux-gnu/libpam.so.0 /lib/libpam.so.0

  # Checks the prerequisites
  - cd /tmp/expc ; ./db2prereqcheck -l
  # Install DB2 and creates an instance (Response file)
  - sudo ./db2setup -r  ${TRAVIS_BUILD_DIR}/db2.rsp || cat /tmp/db2setup.log
  # Changes the security
  - sudo usermod -a -G db2iadm1 $USER
  - sudo chsh -s /bin/bash db2inst1
  - sudo su - db2inst1 -c "db2 update dbm cfg using SYSADM_GROUP db2iadm1 ; db2stop ; db2start"
  # Creates the database
  - sudo su - db2inst1 -c "db2 create db travis ; db2 connect to travis ; db2 grant dbadm on database to user $USER"

  - export DB2DIR=/home/db2inst1/sqllib

  # Install pdo_ibm
  - git clone https://git.php.net/repository/pecl/database/pdo_ibm.git
  - (cd pdo_ibm/; phpize && ./configure --with-pdo-ibm=${DB2DIR} && make && sudo make install)
  - echo "extension=pdo_ibm.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Install ibm_db2
  - git clone https://git.php.net/repository/pecl/database/ibm_db2.git
  - (cd ibm_db2/; phpize && ./configure --with-IBM_DB2=${DB2DIR} && make && sudo make install)
  - echo "extension=ibm_db2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - php -m | grep -i ibm

script:
  # Execute your scripts
  - echo Hello
